"""PySide6 GUI for badchatbot — generated by MetaAgent.

The GUI is OPTIONAL. The same agent also runs:
    python agent.py        # headless CLI
    python server.py       # websocket server + web UI (if generated)

Run the desktop GUI:
    pip install -r requirements.txt
    python gui.py
"""

import copy
import json
import os
import subprocess
import sys
import threading

# Make agent.py importable no matter where Python was launched from
# (also covers PYTHONSAFEPATH / -P environments).
if not getattr(sys, "frozen", False):
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from PySide6.QtCore import Qt, Signal
from PySide6.QtGui import QAction, QFont, QTextCursor
from PySide6.QtWidgets import (
    QApplication,
    QCheckBox,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QFileDialog,
    QHBoxLayout,
    QInputDialog,
    QLabel,
    QLineEdit,
    QListWidget,
    QListWidgetItem,
    QMainWindow,
    QMessageBox,
    QPlainTextEdit,
    QPushButton,
    QScrollArea,
    QVBoxLayout,
    QWidget,
)

import agent as core

_BASE = os.path.dirname(os.path.abspath(__file__))


def _mono() -> QFont:
    f = QFont("Consolas")
    f.setStyleHint(QFont.Monospace)
    f.setPointSize(10)
    return f


class WorkspaceDialog(QDialog):
    """List the workspace folders; add more or remove selected ones."""

    def __init__(self, parent):
        super().__init__(parent)
        self.setWindowTitle("Manage Workspace")
        self.resize(540, 360)
        v = QVBoxLayout(self)
        v.addWidget(QLabel("The agent works on these folders:"))
        self.listbox = QListWidget()
        self.listbox.addItems(core.get_workspace())
        v.addWidget(self.listbox, 1)
        row = QHBoxLayout()
        add_btn = QPushButton("Add Folder...")
        rm_btn = QPushButton("Remove Selected")
        add_btn.clicked.connect(self.on_add)
        rm_btn.clicked.connect(self.on_remove)
        row.addWidget(add_btn)
        row.addWidget(rm_btn)
        row.addStretch(1)
        v.addLayout(row)
        bb = QDialogButtonBox(QDialogButtonBox.Ok)
        bb.accepted.connect(self.accept)
        v.addWidget(bb)

    def _refresh(self):
        self.listbox.clear()
        self.listbox.addItems(core.get_workspace())

    def on_add(self):
        path = QFileDialog.getExistingDirectory(
            self, "Add a folder to the workspace")
        if path:
            core.add_workspace_folder(path)
            self._refresh()

    def on_remove(self):
        i = self.listbox.currentRow()
        if i < 0:
            return
        folders = core.get_workspace()
        del folders[i]
        core.set_workspace(folders)
        self._refresh()


class SkillEditDialog(QDialog):
    """Edit one skill: name + description (the routing hint shown to the agent)
    + body (loaded on demand). Tick 'user-only' to make it /<name>-only."""

    def __init__(self, parent, title, name="", text="", description="",
                 disable_model_invocation=False):
        super().__init__(parent)
        self.setWindowTitle(title)
        self.resize(520, 400)
        v = QVBoxLayout(self)
        row = QHBoxLayout()
        row.addWidget(QLabel("Name:"))
        self.name = QLineEdit(name)
        row.addWidget(self.name, 1)
        v.addLayout(row)
        v.addWidget(QLabel("Description (what it does + when to use it; the only "
                           "part the agent sees until it loads the skill):"))
        self.description = QLineEdit(description)
        v.addWidget(self.description)
        self.manual = QCheckBox("Apply only when the user types /<name> "
                                "(not auto-selected by the agent)")
        self.manual.setChecked(bool(disable_model_invocation))
        v.addWidget(self.manual)
        body_row = QHBoxLayout()
        body_row.addWidget(
            QLabel("Skill body (the full instructions — loaded on demand):"), 1)
        load_btn = QPushButton("Load from .md…")
        load_btn.clicked.connect(self.on_load_md)
        body_row.addWidget(load_btn)
        v.addLayout(body_row)
        self.text = QPlainTextEdit(text)
        v.addWidget(self.text, 1)
        bb = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        bb.accepted.connect(self.accept)
        bb.rejected.connect(self.reject)
        v.addWidget(bb)

    def on_load_md(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Import SKILL.md", "",
            "Markdown (*.md *.markdown *.txt);;All files (*)")
        if not path:
            return
        try:
            with open(path, encoding="utf-8", errors="ignore") as f:
                s = core.parse_skill_md(f.read())
        except OSError as e:
            QMessageBox.warning(self, "Import failed", str(e))
            return
        if s["name"]:
            self.name.setText(s["name"])
        if s["description"]:
            self.description.setText(s["description"])
        self.manual.setChecked(s["disable_model_invocation"])
        self.text.setPlainText(s["text"])

    def values(self):
        return {"name": self.name.text().strip() or "skill",
                "description": self.description.text().strip(),
                "text": self.text.toPlainText().strip(),
                "disable_model_invocation": self.manual.isChecked()}


class SkillsDialog(QDialog):
    """Add / edit / remove an agent's skills at runtime. Changes persist to
    skills.json and apply on the next run."""

    def __init__(self, parent):
        super().__init__(parent)
        self.setWindowTitle("Manage Skills")
        self.resize(620, 500)
        v = QVBoxLayout(self)
        self._agents = core.list_skill_agents()
        row = QHBoxLayout()
        row.addWidget(QLabel("Agent:"))
        self.agent = QComboBox()
        self.agent.addItems(self._agents or ["(none)"])
        self.agent.currentIndexChanged.connect(lambda _i: self._reload())
        row.addWidget(self.agent, 1)
        v.addLayout(row)
        self.listbox = QListWidget()
        v.addWidget(self.listbox, 1)
        h = QHBoxLayout()
        for label, slot in (("Add...", self.on_add), ("Edit...", self.on_edit),
                            ("Remove", self.on_remove)):
            b = QPushButton(label)
            b.clicked.connect(slot)
            h.addWidget(b)
        h.addStretch(1)
        v.addLayout(h)
        bb = QDialogButtonBox(QDialogButtonBox.Ok)
        bb.accepted.connect(self.accept)
        v.addWidget(bb)
        self._reload()

    def _cur_agent(self):
        return self._agents[self.agent.currentIndex()] if self._agents else None

    def _reload(self):
        a = self._cur_agent()
        self._items = list(core.skills_for(a)) if a else []
        self.listbox.clear()
        self.listbox.addItems(
            [(s.get("name") or "skill") + ": "
             + (s.get("text") or "").replace(chr(10), " ")[:48]
             for s in self._items])

    def on_add(self):
        a = self._cur_agent()
        if not a:
            return
        dlg = SkillEditDialog(self, "Add Skill")
        if dlg.exec() == QDialog.Accepted and dlg.values()["text"]:
            r = dlg.values()
            core.add_skill(a, r["name"], r["text"], r["description"],
                           r["disable_model_invocation"])
            self._reload()

    def on_edit(self):
        a = self._cur_agent()
        i = self.listbox.currentRow()
        if not a or i < 0:
            return
        s = self._items[i]
        dlg = SkillEditDialog(self, "Edit Skill", s.get("name", ""),
                              s.get("text", ""), s.get("description", ""),
                              s.get("disable_model_invocation", False))
        if dlg.exec() == QDialog.Accepted and dlg.values()["text"]:
            r = dlg.values()
            core.update_skill(a, i, r["name"], r["text"], r["description"],
                              r["disable_model_invocation"])
            self._reload()

    def on_remove(self):
        a = self._cur_agent()
        i = self.listbox.currentRow()
        if a and i >= 0:
            core.remove_skill(a, i)
            self._reload()


# (label shown in the combo, internal grader type). The runtime grade() supports
# all of these; multi-assertion `checks` arrays are authored in the JSONL/config.
_GRADE_TYPES = [
    ("contains (substring)", "contains"),
    ("equals (exact)", "equals"),
    ("not contains", "not_contains"),
    ("contains all (comma list)", "contains_all"),
    ("contains any (comma list)", "contains_any"),
    ("starts with", "starts_with"),
    ("ends with", "ends_with"),
    ("regex", "regex"),
    ("not regex", "not_regex"),
    ("is JSON", "is_json"),
    ("JSON has keys (comma list)", "json_has_keys"),
    ("numeric (approx value)", "numeric"),
    ("similar (fuzzy)", "similar"),
    ("length (min,max)", "length"),
    ("judge (LLM rubric)", "judge"),
]
_STRING_TYPES = {"contains", "equals", "not_contains", "contains_all",
                 "contains_any", "starts_with", "ends_with"}


class EvalCaseEditDialog(QDialog):
    """Add / edit one eval case: an input plus a typed grader (substring, exact,
    regex, JSON checks, numeric, fuzzy similarity, length, LLM rubric, …). A
    single assertion here; multi-assertion `checks` arrays are authored in the
    evals/*.jsonl file or config.json."""

    def __init__(self, parent, title, case=None):
        super().__init__(parent)
        self.setWindowTitle(title)
        self.resize(540, 480)
        case = case or {}
        v = QVBoxLayout(self)
        row = QHBoxLayout()
        row.addWidget(QLabel("ID:"))
        self.cid = QLineEdit(case.get("id", ""))
        row.addWidget(self.cid, 1)
        v.addLayout(row)
        v.addWidget(QLabel("Input (sent to the agent):"))
        self.input = QPlainTextEdit(case.get("input", ""))
        v.addWidget(self.input, 1)
        row2 = QHBoxLayout()
        row2.addWidget(QLabel("Grade by:"))
        self.grade = QComboBox()
        self.grade.addItems([lbl for lbl, _ in _GRADE_TYPES])
        row2.addWidget(self.grade)
        self.case_sensitive = QCheckBox("case sensitive")
        row2.addWidget(self.case_sensitive)
        row2.addStretch(1)
        v.addLayout(row2)
        v.addWidget(QLabel("Expected value (substring / regex / criterion / "
                           "number / comma-list; ignored for 'is JSON'):"))
        self.expected = QPlainTextEdit()
        v.addWidget(self.expected, 1)
        row3 = QHBoxLayout()
        row3.addWidget(QLabel("Option:"))
        self.option = QLineEdit()
        self.option.setPlaceholderText("similar: threshold 0-1  |  numeric: "
                                       "tolerance  |  length: min,max")
        row3.addWidget(self.option, 1)
        v.addLayout(row3)
        self._preload(case)
        bb = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        bb.accepted.connect(self.accept)
        bb.rejected.connect(self.reject)
        v.addWidget(bb)

    def _preload(self, case):
        # Prefer an explicit single assertion, else the first `checks` entry,
        # else the legacy expected_output / expected_regex / judge fields.
        a = None
        if case.get("type"):
            a = case
        elif isinstance(case.get("checks"), list) and case["checks"]:
            a = case["checks"][0]
        elif case.get("judge"):
            a = {"type": "judge", "value": case["judge"]}
        elif case.get("expected_regex"):
            a = {"type": "regex", "value": case["expected_regex"]}
        elif case.get("expected_output") is not None:
            a = {"type": "contains", "value": case.get("expected_output", "")}
        if not a:
            return
        t = a.get("type", "contains")
        for i, (_lbl, ty) in enumerate(_GRADE_TYPES):
            if ty == t:
                self.grade.setCurrentIndex(i)
                break
        self.case_sensitive.setChecked(bool(a.get("case_sensitive")))
        self.expected.setPlainText(str(a.get("value", "")))
        if t == "length":
            lo, hi = a.get("min"), a.get("max")
            self.option.setText(("" if lo is None else str(lo)) + ","
                                + ("" if hi is None else str(hi)))
        elif t == "similar" and a.get("threshold") is not None:
            self.option.setText(str(a["threshold"]))
        elif t in ("numeric", "close") and a.get("tolerance") is not None:
            self.option.setText(str(a["tolerance"]))

    def values(self):
        t = _GRADE_TYPES[self.grade.currentIndex()][1]
        case = {"id": self.cid.text().strip() or "case",
                "input": self.input.toPlainText().strip(), "type": t}
        val = self.expected.toPlainText().strip()
        opt = self.option.text().strip()
        if t == "is_json":
            pass                                  # no value needed
        elif t == "length":
            lo, _sep, hi = opt.partition(",")
            if lo.strip().lstrip("-").isdigit():
                case["min"] = int(lo.strip())
            if hi.strip().lstrip("-").isdigit():
                case["max"] = int(hi.strip())
        else:
            case["value"] = val
            if opt:
                try:
                    if t == "similar":
                        case["threshold"] = float(opt)
                    elif t == "numeric":
                        case["tolerance"] = float(opt)
                except ValueError:
                    pass
        if self.case_sensitive.isChecked() and t in _STRING_TYPES:
            case["case_sensitive"] = True
        return case


class EvalSetDialog(QDialog):
    """Add / rename an eval set and choose what it tests (one agent, or the
    whole pipeline)."""

    _WHOLE = "(whole pipeline)"

    def __init__(self, parent, title, name="", target=None):
        super().__init__(parent)
        self.setWindowTitle(title)
        self.resize(420, 200)
        v = QVBoxLayout(self)
        row = QHBoxLayout()
        row.addWidget(QLabel("Name:"))
        self.name = QLineEdit(name)
        row.addWidget(self.name, 1)
        v.addLayout(row)
        row2 = QHBoxLayout()
        row2.addWidget(QLabel("Tests:"))
        self._targets = [self._WHOLE] + core.eval_targets()
        self.target = QComboBox()
        self.target.addItems(self._targets)
        self.target.setCurrentText(target if target in self._targets
                                   else self._WHOLE)
        row2.addWidget(self.target, 1)
        v.addLayout(row2)
        bb = QDialogButtonBox(QDialogButtonBox.Ok | QDialogButtonBox.Cancel)
        bb.accepted.connect(self.accept)
        bb.rejected.connect(self.reject)
        v.addWidget(bb)

    def values(self):
        t = self.target.currentText()
        return self.name.text().strip(), (None if t == self._WHOLE else t)


class EvalSetsDialog(QDialog):
    """Edit the eval sets at runtime: add/rename/remove sets, add/edit/remove
    cases. Changes persist to evals.json and apply on the next 'Run Evals'."""

    def __init__(self, parent):
        super().__init__(parent)
        self.setWindowTitle("Edit Eval Sets")
        self.resize(680, 560)
        v = QVBoxLayout(self)
        v.addWidget(QLabel(
            "A set linked to an agent tests that agent alone; a set that tests "
            "the whole pipeline runs end-to-end."))
        cols = QHBoxLayout()

        left = QVBoxLayout()
        left.addWidget(QLabel("Eval sets:"))
        self.sets = QListWidget()
        self.sets.setFixedWidth(230)
        self.sets.currentRowChanged.connect(lambda _i: self._reload_cases())
        left.addWidget(self.sets, 1)
        sb = QHBoxLayout()
        for label, slot in (("Add", self.on_add_set), ("Edit", self.on_edit_set),
                            ("Remove", self.on_remove_set)):
            b = QPushButton(label)
            b.clicked.connect(slot)
            sb.addWidget(b)
        left.addLayout(sb)
        cols.addLayout(left)

        right = QVBoxLayout()
        right.addWidget(QLabel("Cases in the selected set:"))
        self.cases = QListWidget()
        right.addWidget(self.cases, 1)
        cb = QHBoxLayout()
        for label, slot in (("Add Case...", self.on_add_case),
                            ("Edit Case...", self.on_edit_case),
                            ("Remove Case", self.on_remove_case)):
            b = QPushButton(label)
            b.clicked.connect(slot)
            cb.addWidget(b)
        cb.addStretch(1)
        right.addLayout(cb)
        cols.addLayout(right, 1)

        v.addLayout(cols, 1)
        bb = QDialogButtonBox(QDialogButtonBox.Ok)
        bb.accepted.connect(self.accept)
        v.addWidget(bb)
        self._reload_sets()

    def _reload_sets(self, keep=None):
        self.sets.blockSignals(True)
        self.sets.clear()
        self.sets.addItems(
            [f"{s['name']}  \u2192 {s.get('target') or 'whole'}"
             f"  ({len(s.get('cases', []))})" for s in core.EVAL_SETS])
        self.sets.blockSignals(False)
        if core.EVAL_SETS:
            self.sets.setCurrentRow(min(keep if keep is not None else 0,
                                        len(core.EVAL_SETS) - 1))
        self._reload_cases()

    def _cur_set(self):
        i = self.sets.currentRow()
        return i if i >= 0 else None

    def _reload_cases(self):
        i = self._cur_set()
        cases = core.EVAL_SETS[i].get("cases", []) if i is not None else []

        def label(c):
            if isinstance(c.get("checks"), list) and c["checks"]:
                kind = f"{len(c['checks'])} checks"
            else:
                kind = (c.get("type") or ("judge" if c.get("judge") else "regex"
                        if c.get("expected_regex") else "contains"))
            return (f"[{kind}] {c.get('id', '?')}: "
                    + (c.get("input") or "").replace(chr(10), " ")[:46])
        self.cases.clear()
        self.cases.addItems([label(c) for c in cases])

    def on_add_set(self):
        dlg = EvalSetDialog(self, "Add Eval Set")
        if dlg.exec() == QDialog.Accepted:
            name, target = dlg.values()
            core.add_eval_set(name, target)
            self._reload_sets(keep=len(core.EVAL_SETS) - 1)

    def on_edit_set(self):
        i = self._cur_set()
        if i is None:
            return
        s = core.EVAL_SETS[i]
        dlg = EvalSetDialog(self, "Edit Eval Set", s["name"], s.get("target"))
        if dlg.exec() == QDialog.Accepted:
            name, target = dlg.values()
            core.update_eval_set(i, name, target)
            self._reload_sets(keep=i)

    def on_remove_set(self):
        i = self._cur_set()
        if i is not None:
            core.remove_eval_set(i)
            self._reload_sets(keep=max(0, i - 1))

    def on_add_case(self):
        i = self._cur_set()
        if i is None:
            QMessageBox.information(self, "No set", "Add or select an eval set first.")
            return
        dlg = EvalCaseEditDialog(self, "Add Eval Case")
        if dlg.exec() == QDialog.Accepted and dlg.values()["input"]:
            core.add_eval_case(i, dlg.values())
            self._reload_cases()
            self._reload_sets(keep=i)

    def on_edit_case(self):
        i, j = self._cur_set(), self.cases.currentRow()
        if i is None or j < 0:
            return
        case = core.EVAL_SETS[i]["cases"][j]
        dlg = EvalCaseEditDialog(self, "Edit Eval Case", case)
        if dlg.exec() == QDialog.Accepted and dlg.values()["input"]:
            core.update_eval_case(i, j, dlg.values())
            self._reload_cases()

    def on_remove_case(self):
        i, j = self._cur_set(), self.cases.currentRow()
        if i is not None and j >= 0:
            core.remove_eval_case(i, j)
            self._reload_cases()
            self._reload_sets(keep=i)


class RagChunksDialog(QDialog):
    """View / edit / delete the GUI-managed RAG chunks (file-derived chunks
    from the docs folder are part of the index but not listed here)."""

    def __init__(self, parent):
        super().__init__(parent)
        self.setWindowTitle("Manage RAG Knowledge Base")
        self.resize(640, 540)
        v = QVBoxLayout(self)
        docs = core.rag_docs_files() if hasattr(core, "rag_docs_files") else []
        docs_dir = core.RAG.get("docs_dir", "") if hasattr(core, "RAG") else ""
        v.addWidget(QLabel(
            f"Auto-indexed files in the docs folder ({docs_dir or 'not set'}) "
            "— read-only:"))
        self.docs_list = QListWidget()
        self.docs_list.setFixedHeight(110)
        self.docs_list.addItems(docs or ["(none)"])
        v.addWidget(self.docs_list)
        v.addWidget(QLabel("Added chunks (from 'Add File' / 'Add Chunk') — editable:"))
        self.listbox = QListWidget()
        v.addWidget(self.listbox, 1)
        h = QHBoxLayout()
        for label, slot in (("Add File...", self.on_add_file),
                            ("Add Text...", self.on_add),
                            ("Edit...", self.on_edit),
                            ("Delete", self.on_delete),
                            ("Delete File's Chunks", self.on_delete_source)):
            b = QPushButton(label)
            b.clicked.connect(slot)
            h.addWidget(b)
        v.addLayout(h)
        bb = QDialogButtonBox(QDialogButtonBox.Ok)
        bb.accepted.connect(self.accept)
        v.addWidget(bb)
        self._reload()

    def _reload(self):
        self._chunks = core.rag_manual_chunks()
        self.listbox.clear()
        self.listbox.addItems([
            f"#{c['id']} [{c.get('source', 'manual')}] "
            + c.get("text", "").replace(chr(10), " ")[:60]
            for c in self._chunks])

    def on_add_file(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Choose a file to load into the knowledge base", "",
            "Documents (*.txt *.md *.rst *.csv *.json *.html *.log *.py *.pdf "
            "*.docx);;All files (*.*)")
        if path:
            msg = core.rag_add_file(path)
            if msg.startswith("[ERROR]"):
                QMessageBox.warning(self, "Could not add file", msg)
            self._reload()

    def on_delete_source(self):
        i = self.listbox.currentRow()
        if i < 0:
            return
        src = self._chunks[i].get("source", "manual")
        n = core.rag_remove_source(src)
        QMessageBox.information(self, "Deleted", f"Removed {n} chunk(s) from '{src}'.")
        self._reload()

    def _ask_text(self, title, value=""):
        text, ok = QInputDialog.getMultiLineText(self, title, "Chunk text:", value)
        return text if ok else None

    def on_add(self):
        text = self._ask_text("Add Chunk")
        if text and text.strip():
            core.rag_add_chunk(text.strip())
            self._reload()

    def on_edit(self):
        i = self.listbox.currentRow()
        if i < 0:
            return
        text = self._ask_text("Edit Chunk", self._chunks[i].get("text", ""))
        if text is not None:
            core.rag_update_chunk(self._chunks[i]["id"], text)
            self._reload()

    def on_delete(self):
        i = self.listbox.currentRow()
        if i < 0:
            return
        core.rag_delete_chunk(self._chunks[i]["id"])
        self._reload()


class _ToolConfirmDialog(QDialog):
    """Confirm (and optionally EDIT) a high-risk tool call before it runs. The
    full arguments are shown in a resizable, scrollable editor — never trimmed."""

    def __init__(self, parent, tool_name, args):
        super().__init__(parent)
        self.setWindowTitle("Confirm tool call")
        self.resize(680, 540)
        self.setSizeGripEnabled(True)
        self.setWindowFlags(self.windowFlags()
                            | Qt.WindowMaximizeButtonHint | Qt.WindowMinimizeButtonHint)
        self._args = dict(args or {})
        self._decision = "deny"
        # the primary editable argument = the longest string value (e.g. `code`);
        # other args are shown read-only. No string arg -> edit the whole JSON.
        self._pkey, _best = None, -1
        for k, val in self._args.items():
            if isinstance(val, str) and len(val) > _best:
                self._pkey, _best = k, len(val)
        v = QVBoxLayout(self)
        lbl = QLabel(f"The agent wants to run the high-risk tool "
                     f"<b>{tool_name}</b>. Review — and edit if you like — "
                     "before allowing:")
        lbl.setWordWrap(True)
        v.addWidget(lbl)
        others = {k: val for k, val in self._args.items() if k != self._pkey}
        if others:
            v.addWidget(QLabel("Other arguments:"))
            oj = QPlainTextEdit(json.dumps(others, ensure_ascii=False, indent=2))
            oj.setReadOnly(True)
            oj.setMaximumHeight(120)
            v.addWidget(oj)
        v.addWidget(QLabel((self._pkey or "arguments (JSON)") + " — editable:"))
        init = (self._args.get(self._pkey) if self._pkey is not None
                else json.dumps(self._args, ensure_ascii=False, indent=2))
        self.text = QPlainTextEdit(init if isinstance(init, str) else str(init))
        self.text.setFont(QFont("Consolas"))
        v.addWidget(self.text, 1)
        self.remember = QCheckBox(f"Don't ask again for {tool_name} (this run)")
        v.addWidget(self.remember)
        row = QHBoxLayout()
        row.addStretch(1)
        deny = QPushButton("Deny")
        allow_edited = QPushButton("Allow edited")
        allow = QPushButton("Allow")
        deny.clicked.connect(lambda: self._finish("deny"))
        allow_edited.clicked.connect(lambda: self._finish("edit"))
        allow.clicked.connect(lambda: self._finish("allow"))
        for b in (deny, allow_edited, allow):
            row.addWidget(b)
        allow.setDefault(True)
        v.addLayout(row)

    def _finish(self, decision):
        self._decision = decision
        self.accept()

    def outcome(self):
        remember = self.remember.isChecked()
        if self._decision == "deny":
            return {"decision": "deny", "remember": remember}
        args = dict(self._args)
        if self._decision == "edit":
            edited = self.text.toPlainText()
            if self._pkey is not None:
                args[self._pkey] = edited
            else:
                try:
                    parsed = json.loads(edited)
                    if isinstance(parsed, dict):
                        args = parsed
                except Exception:
                    pass                      # unparseable -> keep original args
        return {"decision": "allow", "args": args, "remember": remember}


class _ReviewDialog(QDialog):
    """HITL checkpoint. Two shapes: a GATE review (approve/edit/reject) or, when
    `choices` is given, a route-mode BRANCH picker (one button per next step) — the
    human mirror of a router. Content stays editable in both."""

    def __init__(self, parent, prompt, content, choices=None):
        super().__init__(parent)
        self.setWindowTitle("Human review" if not choices else "Choose the next step")
        self.resize(680, 560)
        self.setSizeGripEnabled(True)
        self.setWindowFlags(self.windowFlags()
                            | Qt.WindowMaximizeButtonHint | Qt.WindowMinimizeButtonHint)
        self._orig = content
        self._choices = list(choices) if choices else None
        self._decision = (self._choices[0] if self._choices else "approve")
        v = QVBoxLayout(self)
        lbl = QLabel(prompt or "Review before continuing.")
        lbl.setWordWrap(True)
        v.addWidget(lbl)
        self.text = QPlainTextEdit(content)
        v.addWidget(self.text, 1)
        if self._choices:                       # ROUTE mode: one button per branch
            v.addWidget(QLabel("Choose the next step (you may edit the text above):"))
            row = QHBoxLayout()
            row.addStretch(1)
            for c in self._choices:
                b = QPushButton(str(c))
                b.clicked.connect(lambda _=False, name=c: self._pick(name))
                row.addWidget(b)
            v.addLayout(row)
        else:                                   # GATE mode: approve / edit / reject
            v.addWidget(QLabel("Rejection feedback:"))
            self.feedback = QLineEdit()
            v.addWidget(self.feedback)
            row = QHBoxLayout()
            row.addStretch(1)
            approve = QPushButton("Approve / Edit")
            reject = QPushButton("Reject")
            approve.clicked.connect(self._approve)
            reject.clicked.connect(self._reject)
            row.addWidget(approve)
            row.addWidget(reject)
            v.addLayout(row)

    def _pick(self, name):
        self._decision = name
        self.accept()

    def _approve(self):
        self._decision = "approve"
        self.accept()

    def _reject(self):
        self._decision = "reject"
        self.accept()

    def outcome(self):
        text = self.text.toPlainText()
        if self._choices:                       # route mode: decision = chosen branch
            return {"decision": self._decision, "content": text, "feedback": ""}
        if self._decision == "reject":
            return {"decision": "reject", "content": self._orig,
                    "feedback": self.feedback.text().strip()}
        if text != self._orig:
            return {"decision": "edit", "content": text, "feedback": ""}
        return {"decision": "approve", "content": self._orig, "feedback": ""}


class _InputEdit(QPlainTextEdit):
    """Multi-line prompt box; Ctrl+Enter submits."""

    submit = Signal()

    def keyPressEvent(self, event):
        if (event.key() in (Qt.Key_Return, Qt.Key_Enter)
                and event.modifiers() & Qt.ControlModifier):
            self.submit.emit()
            return
        super().keyPressEvent(event)


class SettingsDialog(QDialog):
    """Edit the user-facing settings in config.json — per-LLM API key / model /
    base URL / proxy / timeout, the WebSocket server host/port/token, and a couple
    of behaviour toggles. Saving writes config.json and reloads it (new settings
    apply on the next run). Topology, prompts and budgets are baked into agent.py
    and are NOT editable here — re-generate from the canvas to change those."""

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowTitle("Settings")
        self.resize(660, 560)
        outer = QVBoxLayout(self)
        outer.addWidget(QLabel(
            "Settings stored in config.json. Saved changes apply on the next run; "
            "the agent's structure, prompts and budgets are fixed at generation time."))
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        inner = QWidget()
        form = QVBoxLayout(inner)
        scroll.setWidget(inner)
        outer.addWidget(scroll, 1)

        cfg = core.CONFIG
        self._llm_rows = []          # (agent_name, idx, {field_key: QLineEdit})
        for agent_name, cfgs in (cfg.get("llms") or {}).items():
            cfgs = cfgs or []
            for i, lc in enumerate(cfgs):
                tag = "" if len(cfgs) == 1 else "  #%d" % (i + 1)
                form.addWidget(self._heading(
                    "LLM for '%s'%s  (%s)" % (agent_name, tag,
                                              lc.get("model") or lc.get("provider", "?"))))
                fields = {}
                for key, label, ph in (
                        ("api_key", "API key", "sk-..."),
                        ("model", "Model", ""),
                        ("base_url", "Base URL", "blank = provider default"),
                        ("proxy", "Proxy", "http://host:port  ·  blank = system / env"),
                        ("request_timeout_s", "Timeout (s)", "120")):
                    val = lc.get(key)
                    ed = QLineEdit("" if val is None else str(val))
                    if ph:
                        ed.setPlaceholderText(ph)
                    form.addLayout(self._row(label, ed))
                    fields[key] = ed
                self._llm_rows.append((agent_name, i, fields))

        self._srv = {}
        srv = cfg.get("server")
        if isinstance(srv, dict):
            form.addWidget(self._heading("WebSocket server (web UI + client)"))
            for key, label, default in (("host", "Host", "127.0.0.1"),
                                        ("port", "Port (listen)", "8765"),
                                        ("auth_token", "Auth token", "")):
                ed = QLineEdit(str(srv.get(key, default)))
                form.addLayout(self._row(label, ed))
                self._srv[key] = ed

        form.addWidget(self._heading("Behaviour"))
        self.hitl = QCheckBox("Confirm before running risky tools (human-in-the-loop)")
        self.hitl.setChecked(bool(cfg.get("hitl_confirm", True)))
        form.addWidget(self.hitl)
        self.stream = QCheckBox("Stream responses token-by-token")
        self.stream.setChecked(bool(cfg.get("stream", True)))
        form.addWidget(self.stream)
        form.addStretch(1)

        bb = QDialogButtonBox(QDialogButtonBox.Save | QDialogButtonBox.Cancel)
        bb.accepted.connect(self.accept)
        bb.rejected.connect(self.reject)
        outer.addWidget(bb)

    @staticmethod
    def _heading(text):
        lab = QLabel(text)
        f = lab.font()
        f.setBold(True)
        lab.setFont(f)
        lab.setContentsMargins(0, 10, 0, 2)
        return lab

    @staticmethod
    def _row(label, widget):
        row = QHBoxLayout()
        lab = QLabel(label)
        lab.setMinimumWidth(96)
        row.addWidget(lab)
        row.addWidget(widget, 1)
        return row

    def collect(self):
        """A new config dict with the edits applied — deep-copied from CONFIG so
        every untouched key (guardrails, code_exec, budgets baked in config, ...)
        is preserved exactly."""
        new = copy.deepcopy(core.CONFIG)
        for agent_name, i, fields in self._llm_rows:
            lc = new["llms"][agent_name][i]
            lc["api_key"] = fields["api_key"].text().strip()
            lc["model"] = fields["model"].text().strip()
            lc["base_url"] = fields["base_url"].text().strip()
            proxy = fields["proxy"].text().strip()
            if proxy:
                lc["proxy"] = proxy
            else:
                lc.pop("proxy", None)            # blank → fall back to env / direct
            t = fields["request_timeout_s"].text().strip()
            if t:
                try:
                    lc["request_timeout_s"] = float(t)
                except ValueError:
                    pass
        if self._srv:
            srv = new.setdefault("server", {})
            srv["host"] = self._srv["host"].text().strip() or "127.0.0.1"
            ptxt = self._srv["port"].text().strip()
            if ptxt:
                try:
                    srv["port"] = int(float(ptxt))
                except ValueError:
                    pass
            srv["auth_token"] = self._srv["auth_token"].text().strip()
        new["hitl_confirm"] = self.hitl.isChecked()
        new["stream"] = self.stream.isChecked()
        return new


class ChatFrame(QMainWindow):
    """The desktop chat window for the agent."""

    # worker-thread -> GUI-thread signals (Qt queues them onto the GUI thread)
    _sig_append = Signal(str)
    _sig_token = Signal(str)
    _sig_status = Signal(str)
    _sig_done = Signal(object)
    _sig_fail = Signal(str)
    _sig_eval_done = Signal(object)
    _sig_eval_fail = Signal(str)
    _sig_confirm = Signal(object)   # blocking HITL confirm payload
    _sig_review = Signal(object)    # blocking HITL review payload

    def __init__(self):
        super().__init__()
        self.setWindowTitle("badchatbot")
        self.resize(820, 640)
        self._server_proc = None
        self._attachments = []
        self._vision = bool(hasattr(core, "entry_vision") and core.entry_vision())

        self._sig_append.connect(self.append)
        self._sig_token.connect(self._insert_raw)
        self._sig_status.connect(self.statusBar().showMessage)
        self._sig_done.connect(self._done)
        self._sig_fail.connect(self._fail)
        self._sig_eval_done.connect(self._eval_done)
        self._sig_eval_fail.connect(self._eval_fail)
        self._sig_confirm.connect(self._show_confirm)
        self._sig_review.connect(self._show_review)

        self._build_menu()
        self._build_ui()
        if hasattr(core, "set_confirm_handler"):
            core.set_confirm_handler(self._confirm_tool)
        if hasattr(core, "set_review_handler"):
            core.set_review_handler(self._review)
        self._show_workspace_status()
        self._replay_history()
        self._maybe_autostart_server()

    # ── UI ──────────────────────────────────────────────────────────────────
    def _build_ui(self):
        root = QWidget()
        self.setCentralWidget(root)
        v = QVBoxLayout(root)

        self.output = QPlainTextEdit()
        self.output.setReadOnly(True)
        self.output.setFont(_mono())
        v.addWidget(self.output, 1)

        if self._vision:
            self.attach_lbl = QLabel("")
            self.attach_lbl.setStyleSheet("color:#5a5a5a;")
            v.addWidget(self.attach_lbl)
            self.setAcceptDrops(True)   # drag image files onto the window

        row = QHBoxLayout()
        self.input = _InputEdit()
        self.input.setPlaceholderText("Type a task, Ctrl+Enter to send")
        self.input.setFixedHeight(70)
        self.input.submit.connect(self.on_send)
        row.addWidget(self.input, 1)
        if self._vision:
            self.attach_btn = QPushButton("Attach\nImage")
            self.attach_btn.clicked.connect(self.on_attach)
            row.addWidget(self.attach_btn)
        self.send_btn = QPushButton("Send")
        self.send_btn.clicked.connect(self.on_send)
        row.addWidget(self.send_btn)
        self.stop_btn = QPushButton("Stop")
        self.stop_btn.setEnabled(False)
        self.stop_btn.clicked.connect(self.on_stop)
        row.addWidget(self.stop_btn)
        v.addLayout(row)
        self.statusBar()
        # Permanent (right-side) readout of token usage + context — not cleared by
        # transient showMessage() updates, so it stays visible at all times.
        self._meta_label = QLabel()
        self.statusBar().addPermanentWidget(self._meta_label)
        self._update_meta()
        if self._vision:
            # The output/input QPlainTextEdits accept drops by default and would
            # otherwise swallow image-file drops before they reach the window's
            # dropEvent (wx installed the drop target on both). Disable theirs so
            # drops bubble up to ChatFrame.dropEvent.
            self.output.setAcceptDrops(False)
            self.input.setAcceptDrops(False)

    # ── drag & drop (vision) ────────────────────────────────────────────────
    def dragEnterEvent(self, event):
        if self._vision and event.mimeData().hasUrls():
            event.acceptProposedAction()

    def dropEvent(self, event):
        if not self._vision:
            return
        imgs = [u.toLocalFile() for u in event.mimeData().urls()
                if os.path.splitext(u.toLocalFile())[1].lower() in core.IMAGE_EXTS]
        if imgs:
            self._add_attachments(imgs)
            event.acceptProposedAction()

    # ── HITL confirm / review (thread-safe, blocking) ───────────────────────
    def _confirm_tool(self, tool_name, args):
        payload = {"tool": tool_name, "args": args, "done": threading.Event(),
                   "res": {"decision": "deny"}}
        self._sig_confirm.emit(payload)
        payload["done"].wait()
        return payload["res"]

    def _show_confirm(self, payload):
        try:
            dlg = _ToolConfirmDialog(self, payload["tool"], payload["args"])
            dlg.exec()
            payload["res"] = dlg.outcome()
        finally:
            payload["done"].set()

    def _review(self, prompt, content, choices=None):
        payload = {"prompt": prompt, "content": content, "choices": choices,
                   "done": threading.Event(),
                   "res": {"decision": (choices[0] if choices else "approve"),
                           "content": content, "feedback": ""}}
        self._sig_review.emit(payload)
        payload["done"].wait()
        return payload["res"]

    def _show_review(self, payload):
        try:
            dlg = _ReviewDialog(self, payload["prompt"], payload["content"],
                                payload.get("choices"))
            dlg.exec()
            payload["res"] = dlg.outcome()
        finally:
            payload["done"].set()

    # ── output helpers ──────────────────────────────────────────────────────
    def _insert_raw(self, text):
        self.output.moveCursor(QTextCursor.End)
        self.output.insertPlainText(text)
        self.output.moveCursor(QTextCursor.End)

    def append(self, text):
        self._insert_raw(text.rstrip() + "\n")

    def _replay_history(self):
        history = getattr(core, "HISTORY", [])
        for h in history:
            if h.get("role") == "user":
                self.append(f"You:\n{h.get('content', '')}\n")
            else:
                self.append(f"=== Final Result ===\n{h.get('content', '')}\n")
        if history:
            self.append(f"[history] resumed {len(history) // 2} earlier "
                        "exchange(s) — use the History menu to clear.\n")

    def on_clear_history(self):
        if QMessageBox.question(
                self, "Confirm",
                "Clear the stored conversation history?") != QMessageBox.Yes:
            return
        core.clear_history()
        self.output.setPlainText("")
        self.append("[history] cleared.")
        self._update_meta()

    # ── sessions (recent / recover / new) ──────────────────────────────────
    def _rebuild_session_menu(self):
        m = self._session_menu
        m.clear()
        m.addAction("&New Session").triggered.connect(self.on_new_session)
        m.addSeparator()
        try:
            sessions = core.list_sessions()
        except Exception:
            sessions = []
        if not sessions:
            m.addAction("(no sessions yet)").setEnabled(False)
        for s in sessions[:10]:
            mark = "\u25CF " if s.get("active") else "\u25CB "
            when = ("  \u2014 " + s["updated"]) if s.get("updated") else ""
            act = m.addAction(mark + (s.get("title") or "(session)") + when)
            act.triggered.connect(
                lambda checked=False, i=s["id"]: self.on_load_session(i))

    def on_new_session(self):
        core.new_session()
        self.output.setPlainText("")
        self._replay_history()
        self._update_meta()
        self.statusBar().showMessage("Started a new session.")

    def on_load_session(self, sid):
        if core.load_session(sid):
            self.output.setPlainText("")
            self._replay_history()
            self._update_meta()
            self.statusBar().showMessage("Recovered session.")

    # ── settings (edit config.json) / reload / MCP ──────────────────────────
    def on_edit_settings(self):
        dlg = SettingsDialog(self)
        if dlg.exec() != QDialog.Accepted:
            return
        try:
            core.save_config(dlg.collect())
        except Exception as e:
            QMessageBox.warning(self, "Could not save settings", str(e))
            return
        self.append("[settings] saved to config.json and reloaded; new settings "
                    "apply to the next run.")
        self._sig_status.emit("Settings saved.")

    def on_reload_config(self):
        core.reload_config()
        self.append("[reload] config.json reloaded; new settings apply to the "
                    "next run.")
        self._sig_status.emit("Config reloaded.")

    def on_reconnect_mcp(self):
        self.append("[mcp] reconnecting to MCP server(s)...")
        self._sig_status.emit("Reconnecting MCP...")

        def work():
            try:
                if hasattr(core, "reload_config"):
                    core.reload_config()
                core.mcp_reconnect(emit=lambda s: self._sig_append.emit(s))
                self._sig_status.emit("MCP reconnected.")
            except Exception as e:
                self._sig_append.emit(f"[mcp] reconnect failed: {e}")
                self._sig_status.emit("MCP reconnect failed.")

        threading.Thread(target=work, daemon=True).start()

    # ── WebSocket server (runs server.py as a subprocess) ───────────────────
    def on_toggle_server(self, checked):
        if checked:
            self._start_server()
        else:
            self._stop_server()

    def _maybe_autostart_server(self):
        """config.json -> server.autostart: open the WebSocket port on launch (checks
        the Server action -> spawns server.py) instead of waiting for the menu. The
        headless server.py ALWAYS listens on start, so this only affects the desktop
        app. No-op in the frozen build (start server.py separately) or if server.py
        wasn't generated (no WebServer node)."""
        if not core.CONFIG.get("server", {}).get("autostart"):
            return
        if getattr(sys, "frozen", False):
            return
        if not os.path.isfile(os.path.join(_BASE, "server.py")):
            return
        self._srv_action.setChecked(True)     # -> on_toggle_server -> _start_server

    def _start_server(self):
        if self._server_proc and self._server_proc.poll() is None:
            return
        if getattr(sys, "frozen", False):
            QMessageBox.information(
                self, "Not available here",
                "In the packaged app, start the server separately "
                "(python server.py in the agent folder).")
            self._srv_action.setChecked(False)
            return
        self._server_proc = subprocess.Popen(
            [sys.executable, os.path.join(_BASE, "server.py")], cwd=_BASE)
        cfg = core.CONFIG.get("server", {})
        host = cfg.get("host", "127.0.0.1")
        port = cfg.get("port", 8765)
        self.append(f"[server] starting on ws://{host}:{port} — open "
                    f"http://{host}:{port}/ in a browser for the web UI "
                    "(ready in a few seconds)...")
        self._sig_status.emit(f"WebSocket server + web UI: http://{host}:{port}/")

    def _stop_server(self, quiet=False):
        running = bool(self._server_proc and self._server_proc.poll() is None)
        if running:
            self._server_proc.kill()
        self._server_proc = None
        # Only report a stop when one was actually running, so the frozen-app
        # decline path (which reverts the checkable action, re-emitting toggled)
        # doesn't print a spurious "[server] stopped." line.
        if not quiet and running:
            self.append("[server] stopped.")
            self._show_workspace_status()

    def closeEvent(self, event):
        self._stop_server(quiet=True)
        super().closeEvent(event)

    # ── menus ───────────────────────────────────────────────────────────────
    def _build_menu(self):
        mb = self.menuBar()
        ws_menu = mb.addMenu("&Workspace")
        a_set = ws_menu.addAction("&Set Workspace Folder...")
        a_set.setShortcut("Ctrl+W")
        a_set.triggered.connect(self.on_set_workspace)
        ws_menu.addAction("&Add Folder...").triggered.connect(self.on_add_folder)
        ws_menu.addAction("&Manage Workspace...").triggered.connect(
            self.on_manage_workspace)

        self._build_llm_menu(mb)

        if hasattr(core, "list_sessions"):
            self._session_menu = mb.addMenu("&Session")
            self._session_menu.aboutToShow.connect(self._rebuild_session_menu)
            self._rebuild_session_menu()

        if hasattr(core, "clear_history"):
            hist_menu = mb.addMenu("&History")
            hist_menu.addAction("&Clear History").triggered.connect(
                self.on_clear_history)

        if hasattr(core, "reload_config"):
            settings_menu = mb.addMenu("&Settings")
            if hasattr(core, "save_config"):
                settings_menu.addAction("&Edit Settings...").triggered.connect(
                    self.on_edit_settings)
                settings_menu.addSeparator()
            settings_menu.addAction("Reload &Config (config.json)").triggered.connect(
                self.on_reload_config)
            if core.CONFIG.get("mcp_servers") and hasattr(core, "mcp_reconnect"):
                settings_menu.addAction("Reconnect &MCP Server(s)").triggered.connect(
                    self.on_reconnect_mcp)

        if (core.CONFIG.get("server")
                and os.path.exists(os.path.join(_BASE, "server.py"))):
            srv_menu = mb.addMenu("&Server")
            self._srv_action = srv_menu.addAction("&Enable WebSocket Server")
            self._srv_action.setCheckable(True)
            self._srv_action.toggled.connect(self.on_toggle_server)

        if core.CONFIG.get("rag") and hasattr(core, "rag_enabled"):
            rag_menu = mb.addMenu("&RAG")
            self._rag_action = rag_menu.addAction("&Enable RAG")
            self._rag_action.setCheckable(True)
            self._rag_action.setChecked(core.rag_enabled())
            self._rag_action.toggled.connect(self.on_rag_toggle)
            rag_menu.addSeparator()
            rag_menu.addAction("Add &File...").triggered.connect(self.on_rag_add_file)
            rag_menu.addAction("&Add Chunk (paste text)...").triggered.connect(
                self.on_rag_add)
            rag_menu.addAction("&Manage Knowledge Base...").triggered.connect(
                self.on_rag_manage)
            rag_menu.addAction("&Rebuild Index").triggered.connect(self.on_rag_rebuild)
            rag_menu.addAction("&Clear Knowledge Base (added items)").triggered.connect(
                self.on_rag_clear)

        if core.CONFIG.get("skills") and hasattr(core, "list_skill_agents"):
            sk_menu = mb.addMenu("S&kills")
            sk_menu.addAction("&Manage Skills...").triggered.connect(
                self.on_manage_skills)

        if hasattr(core, "run_evals"):
            ev_menu = mb.addMenu("&Evals")
            self._eval_action = ev_menu.addAction("&Run Evals")
            self._eval_action.setShortcut("Ctrl+E")
            self._eval_action.triggered.connect(self.on_run_evals)
            ev_menu.addAction("&Edit Eval Sets...").triggered.connect(
                self.on_edit_evals)

    def _build_llm_menu(self, mb):
        """One submenu per agent that has more than one linked LLM: radio items
        switch the active LLM, and a checkable 'Lock to selected' item makes that
        choice authoritative (manual mode — no failover to the others)."""
        if not hasattr(core, "get_llm_options"):
            return
        switchable = [a for a in core.PIPELINE
                      if len(core.get_llm_options(a)) > 1]
        if not switchable:
            return
        from PySide6.QtGui import QActionGroup
        menu = mb.addMenu("&LLM")
        self._llm_groups = []
        for agent_name in switchable:
            sub = menu.addMenu(agent_name)
            group = QActionGroup(self)
            group.setExclusive(True)
            self._llm_groups.append(group)
            current = core.get_llm_choice(agent_name)
            for i, model in enumerate(core.get_llm_options(agent_name)):
                act = sub.addAction(f"{i + 1}. {model}")
                act.setCheckable(True)
                if i == current:
                    act.setChecked(True)
                group.addAction(act)
                act.triggered.connect(
                    lambda checked=False, a=agent_name, idx=i:
                    self.on_llm_choice(a, idx))
            if hasattr(core, "get_llm_mode"):
                sub.addSeparator()
                lock = sub.addAction("Lock to selected (no fallback)")
                lock.setCheckable(True)
                lock.setChecked(core.get_llm_mode(agent_name) == "manual")
                lock.triggered.connect(
                    lambda checked=False, a=agent_name:
                    self.on_llm_lock(a, checked))

    def on_llm_choice(self, agent_name, idx):
        core.set_llm_choice(agent_name, idx)
        model = core.get_llm_options(agent_name)[idx]
        suffix = (" [locked — no fallback]"
                  if getattr(core, "get_llm_mode", lambda _a: "fallback")(
                      agent_name) == "manual" else "")
        self.append(f"[llm] {agent_name} now uses: {model}{suffix}")

    def on_llm_lock(self, agent_name, locked):
        core.set_llm_mode(agent_name, "manual" if locked else "fallback")
        state = ("locked to the selected model (no fallback)" if locked
                 else "fallback enabled (tries the other LLMs on error)")
        self.append(f"[llm] {agent_name}: {state}")

    def _show_workspace_status(self):
        folders = core.get_workspace()
        self._sig_status.emit(
            "Workspace: " + ("; ".join(folders) if folders
                             else "(not set — Workspace menu)"))

    def on_set_workspace(self):
        path = QFileDialog.getExistingDirectory(self, "Choose the workspace folder")
        if path:
            core.set_workspace([path])
            self.append(f"[workspace] set to: {path}")
        self._show_workspace_status()

    def on_add_folder(self):
        path = QFileDialog.getExistingDirectory(self, "Add a folder to the workspace")
        if path:
            folders = core.add_workspace_folder(path)
            self.append("[workspace] folders: " + "; ".join(folders))
        self._show_workspace_status()

    def on_manage_workspace(self):
        WorkspaceDialog(self).exec()
        self._show_workspace_status()

    # ── RAG menu ────────────────────────────────────────────────────────────
    def on_rag_toggle(self, on):
        core.set_rag_enabled(on)
        self.append(f"[rag] {'enabled' if on else 'disabled'}.")

    def on_rag_add(self):
        text, ok = QInputDialog.getMultiLineText(
            self, "Add RAG Chunk",
            "Text of the chunk to add to the knowledge base:", "")
        if ok and text.strip():
            self.append("[rag] " + core.rag_add_chunk(text.strip()))

    def on_rag_add_file(self):
        path, _ = QFileDialog.getOpenFileName(
            self, "Choose a file to load into the knowledge base", "",
            "Documents (*.txt *.md *.rst *.csv *.json *.html *.log *.py *.pdf "
            "*.docx);;All files (*.*)")
        if path:
            self.append("[rag] " + core.rag_add_file(path))

    def on_rag_manage(self):
        RagChunksDialog(self).exec()
        self.append("[rag] chunk store updated.")

    def on_rag_rebuild(self):
        core.rag_invalidate()
        self.append("[rag] index cleared — it will rebuild on the next search.")

    def on_rag_clear(self):
        if QMessageBox.question(
                self, "Clear knowledge base",
                "Delete ALL manually-added RAG chunks?") == QMessageBox.Yes:
            core.rag_clear()
            self.append("[rag] manual chunks cleared.")

    def on_manage_skills(self):
        SkillsDialog(self).exec()
        self.append("[skills] updated — applied on the next run.")

    def on_edit_evals(self):
        EvalSetsDialog(self).exec()
        n = sum(len(s.get("cases", [])) for s in core.EVAL_SETS)
        self.append(f"[eval] {len(core.EVAL_SETS)} set(s), {n} case(s) "
                    "— saved to evals.json.")

    # ── image attachments (vision) ──────────────────────────────────────────
    def _add_attachments(self, paths):
        self._attachments.extend(paths)
        self._update_attach_label()

    def _update_attach_label(self):
        if not self._vision:
            return
        n = len(self._attachments)
        names = ", ".join(os.path.basename(p) for p in self._attachments)
        self.attach_lbl.setText(f"\U0001F4CE {n} image(s): {names}" if n else "")

    def on_attach(self):
        paths, _ = QFileDialog.getOpenFileNames(
            self, "Attach image(s)", "",
            "Images (*.png *.jpg *.jpeg *.gif *.webp *.bmp);;All files (*.*)")
        if paths:
            self._add_attachments(paths)

    # ── run ─────────────────────────────────────────────────────────────────
    def on_send(self):
        task = self.input.toPlainText().strip()
        if not task:
            return
        self.input.setPlainText("")
        images = list(self._attachments)
        self._attachments = []
        self._update_attach_label()
        note = (f"  [\U0001F4CE {len(images)} image(s)]" if images else "")
        self.append(f"You:\n{task}{note}\n")
        self.send_btn.setEnabled(False)
        if hasattr(self, "_eval_action"):     # a run is single-flight — block evals
            self._eval_action.setEnabled(False)   # while a chat turn is in flight
        if hasattr(core, "request_cancel"):
            self.stop_btn.setEnabled(True)
        self._sig_status.emit("Working...  (Stop to interrupt)")
        threading.Thread(target=self._worker, args=(task, images),
                         daemon=True).start()

    def on_stop(self):
        if hasattr(core, "request_cancel"):
            core.request_cancel()
            self.stop_btn.setEnabled(False)
            self._sig_status.emit("Stopping...")

    def _worker(self, task, images=None):
        try:
            result = core.run(
                task,
                emit=lambda s: self._sig_append.emit(s),
                on_token=lambda d: self._sig_token.emit(d),
                images=images or None)
            self._sig_done.emit(result)
        except Exception as e:
            self._sig_fail.emit(str(e))

    def _done(self, result):
        self.append(f"\n=== Final Result ===\n{result}\n")
        self.send_btn.setEnabled(True)
        if hasattr(self, "_eval_action"):
            self._eval_action.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self._sig_status.emit("Ready.")
        self._update_meta()

    def _update_meta(self):
        """Refresh the always-on token/context readout (right of the status bar)."""
        parts = []
        if hasattr(core, "total_usage"):
            u = core.total_usage()
            parts.append(f"Session: {u['input_tokens']} in + "
                         f"{u['output_tokens']} out tokens")
        if hasattr(core, "context_usage"):
            c = core.context_usage()
            tok, capn = c.get("tokens", 0), c.get("capacity", 0)
            if capn:
                parts.append(f"Context: ~{tok / 1000:.1f}k / {capn // 1000}k "
                             f"({int(100 * tok / capn)}%)")
            elif tok:
                parts.append(f"Context: ~{tok / 1000:.1f}k")
        self._meta_label.setText("    |    ".join(parts))

    def _fail(self, err):
        self.append(f"\n[ERROR] {err}\n")
        self.send_btn.setEnabled(True)
        if hasattr(self, "_eval_action"):
            self._eval_action.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self._sig_status.emit("Error - check config.json / network.")

    # ── evals ─────────────────────────────────────────────────────────────────
    def on_run_evals(self):
        self._eval_action.setEnabled(False)
        self.send_btn.setEnabled(False)
        if hasattr(core, "request_cancel"):
            self.stop_btn.setEnabled(True)
        self.append("\n=== Running evals ===")
        self._sig_status.emit("Running evals...  (Stop to interrupt)")
        threading.Thread(target=self._eval_worker, daemon=True).start()

    def _eval_worker(self):
        try:
            results = core.run_evals(emit=lambda s: self._sig_append.emit(s))
            self._sig_eval_done.emit(results)
        except Exception as e:
            self._sig_eval_fail.emit(str(e))

    def _eval_done(self, results):
        passed = sum(r["passed"] for r in results)
        total = sum(r["total"] for r in results)
        score = passed / total if total else 0.0
        self.append(f"=== Evals done: {passed}/{total} = {score:.2f} ===\n"
                    if results else "=== No eval sets found ===\n")
        self._eval_action.setEnabled(True)
        self.send_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self._sig_status.emit(
            f"Evals: {passed}/{total} passed ({score:.0%})"
            if results else "No eval sets found.")

    def _eval_fail(self, err):
        self.append(f"\n[eval ERROR] {err}\n")
        self._eval_action.setEnabled(True)
        self.send_btn.setEnabled(True)
        self.stop_btn.setEnabled(False)
        self._sig_status.emit("Eval error - check config.json / network.")


if __name__ == "__main__":
    app = QApplication.instance() or QApplication(sys.argv)
    win = ChatFrame()
    win.show()
    sys.exit(app.exec())
