"""WebSocket server + web UI for ppbb — generated by MetaAgent.

Run:
    python server.py

Then EITHER open http://host:port/ in a browser (built-in chat web UI),
or connect a WebSocket client directly.

Protocol (JSON text frames over ws://host:port):
    client → {"type": "auth", "token": "..."}      (only if auth_token is set)
    client → {"type": "task", "task": "...",       run the agent
              "images": ["data:image/png;base64,..."],  (vision only, optional)
              "session_id": "..."}                 (optional: pin a conversation;
                                                    else each connection is its own)
    client → {"type": "cancel"}                     stop the in-flight run
    client → {"type": "ping"}                      health check
    client → {"type": "hitl_response", "id": n,     answer a HITL prompt:
              "result": true|false                   tool confirm (bool), or
                        |{"decision":..,"content":..,"feedback":..}}  review
    server → {"type": "hello", "vision": bool, ...}  on connect
    server → {"type": "trace", "text": "..."}      live step traces
    server → {"type": "hitl_confirm", "id": n, "prompt": "..."}  approve a tool
    server → {"type": "hitl_review", "id": n,       human review of a stage:
              "prompt": "...", "content": "..."}      reply with hitl_response
    server → {"type": "result", "result": "..."}   final answer
    server → {"type": "error", "error": "..."}

Settings live in config.json under "server": host, port, auth_token,
auto_allow_tools. HITL now does a real browser round-trip: high-risk tool calls
and review checkpoints prompt the connected web client and block the run until
it answers. Set auto_allow_tools=true to skip prompting (auto-approve), e.g. for
a headless/automated client; if the client disconnects mid-prompt the run is
cancelled (tools denied, reviews rejected).
"""

import asyncio
import http
import io
import json
import mimetypes
import os
import sys
import threading
import zipfile
from urllib.parse import parse_qs, unquote, urlsplit

if not getattr(sys, "frozen", False):
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import websockets
from websockets.datastructures import Headers
from websockets.http11 import Response

import agent as core

INDEX_HTML = """<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>ppbb</title>
<style>
  body{font-family:'Segoe UI',system-ui,sans-serif;margin:0;background:#f5f5f5;
       display:flex;flex-direction:column;height:100vh}
  header{background:#1565c0;color:#fff;padding:10px 16px;display:flex;
         justify-content:space-between;align-items:center}
  #status{font-size:13px;opacity:.9}
  #log{flex:1;overflow-y:auto;padding:16px;display:flex;
       flex-direction:column;gap:8px}
  .msg{max-width:85%;padding:8px 12px;border-radius:8px;
       white-space:pre-wrap;word-break:break-word}
  .user{align-self:flex-end;background:#1565c0;color:#fff}
  .result{align-self:flex-start;background:#fff;border:1px solid #ddd}
  .trace{align-self:stretch;max-width:100%;background:#eceff1;color:#546e7a;
         font-family:Consolas,monospace;font-size:12px}
  .error{align-self:stretch;max-width:100%;background:#ffebee;color:#b71c1c}
  footer{display:flex;gap:8px;padding:12px;background:#fff;
         border-top:1px solid #ddd}
  textarea{flex:1;resize:none;height:60px;padding:8px;font:inherit}
  button{padding:0 24px;background:#1565c0;color:#fff;border:none;
         border-radius:6px;cursor:pointer;font:inherit}
  button:disabled{background:#90a4ae}
</style></head>
<body>
<header><b>ppbb</b><span style="display:flex;gap:16px;align-items:center">
  <span id="ws" title="Folder on the server where the agent reads and writes files. Click to set." style="font-size:13px;cursor:pointer;opacity:.95;text-decoration:underline dotted">📁 workspace: (not set)</span>
  <span id="status">connecting…</span></span></header>
<div id="log"></div>
<div id="attachbar" style="display:none;padding:4px 12px;font-size:13px;color:#555;background:#fff;border-top:1px solid #eee"></div>
<div id="files" style="display:none;padding:6px 12px;font-size:13px;background:#fff;border-top:1px solid #eee"></div>
<footer>
  <textarea id="input" placeholder="Type a task — Ctrl+Enter to send"></textarea>
  <input type="file" id="file" accept="image/png,image/jpeg,image/gif,image/webp,image/bmp" multiple style="display:none">
  <button id="attach" title="Attach image(s)" style="display:none">📎</button>
  <button id="send" disabled>Send</button>
  <button id="stop" disabled>Stop</button>
</footer>
<script>
const log = document.getElementById("log");
const input = document.getElementById("input");
const send = document.getElementById("send");
const stop = document.getElementById("stop");
const status = document.getElementById("status");
const wsLabel = document.getElementById("ws");
let curWs = [];
function showWs(folders) {
  curWs = folders || [];
  wsLabel.textContent = "📁 workspace: " + (curWs.length ? curWs.join("; ") : "(not set)");
}
wsLabel.onclick = () => {
  if (ws.readyState !== 1) return;
  const p = prompt("Workspace folder — an ABSOLUTE path on the server where the agent reads and writes files (blank to clear):", curWs[0] || "");
  if (p === null) return;
  ws.send(JSON.stringify({type: "set_workspace", folders: p.trim() ? [p.trim()] : []}));
};
const fileInput = document.getElementById("file");
const attach = document.getElementById("attach");
const attachbar = document.getElementById("attachbar");
let busy = false;
let visionOn = false;
let pending = [];          // attached images as base64 data URLs

let streamBubble = null;   // live result bubble being filled by tokens

const filesBar = document.getElementById("files");
let authToken = "";
function esc(s) { return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;"); }
function fmtSize(n) { if (n < 1024) return n + " B"; if (n < 1048576) return (n / 1024).toFixed(1) + " KB"; return (n / 1048576).toFixed(1) + " MB"; }
function renderFiles(items) {
  if (!items || !items.length) { filesBar.style.display = "none"; filesBar.innerHTML = ""; return; }
  const tok = authToken ? "&token=" + encodeURIComponent(authToken) : "";
  let html = "📂 files: ";
  if (items.length >= 2) {
    html += '<a href="/zip' + (authToken ? "?token=" + encodeURIComponent(authToken) : "")
          + '" download="workspace.zip" style="margin-right:14px;font-weight:bold">⬇ all (.zip)</a>';
  }
  html += items.map(f =>
    '<a href="/download?path=' + encodeURIComponent(f.path) + tok + '" download style="margin-right:14px">'
    + esc(f.name) + " (" + fmtSize(f.size) + ")</a>").join("");
  filesBar.style.display = "block";
  filesBar.innerHTML = html;
}
function addFileLinks(produced) {
  if (!produced || !produced.length) return;
  const tok = authToken ? "&token=" + encodeURIComponent(authToken) : "";
  const d = document.createElement("div");
  d.className = "msg result"; d.style.fontSize = "13px";
  d.innerHTML = "📎 produced: " + produced.map(f =>
    '<a href="/download?path=' + encodeURIComponent(f.path) + tok + '" download style="margin-right:12px">'
    + esc(f.name) + " (" + fmtSize(f.size) + ")</a>").join("");
  log.appendChild(d); log.scrollTop = log.scrollHeight;
}
function refreshFiles() {
  const tok = authToken ? "?token=" + encodeURIComponent(authToken) : "";
  fetch("/files" + tok).then(r => r.ok ? r.json() : {files: []}).then(d => renderFiles(d.files || [])).catch(() => {});
}

function refreshAttachbar() {
  if (pending.length) {
    attachbar.style.display = "block";
    attachbar.textContent = "📎 " + pending.length +
      " image(s) attached — sent with your next message";
  } else { attachbar.style.display = "none"; attachbar.textContent = ""; }
}

function addFiles(files) {
  for (const f of files) {
    if (!f.type.startsWith("image/")) continue;
    const r = new FileReader();
    r.onload = () => { pending.push(r.result); refreshAttachbar(); };
    r.readAsDataURL(f);
  }
}

function add(cls, text) {
  const d = document.createElement("div");
  d.className = "msg " + cls;
  d.textContent = text;
  log.appendChild(d);
  log.scrollTop = log.scrollHeight;
  return d;
}

const ws = new WebSocket("ws://" + location.host + "/");
ws.onopen = () => { status.textContent = "connected"; };
ws.onclose = () => { status.textContent = "disconnected — restart server.py and reload"; send.disabled = true; stop.disabled = true; };
ws.onmessage = (ev) => {
  const m = JSON.parse(ev.data);
  if (m.type === "hello") {
    visionOn = !!m.vision;
    showWs(m.workspace);
    if (visionOn) attach.style.display = "";
    if (m.auth_required) {
      authToken = prompt("This agent requires an auth token:") || "";
      ws.send(JSON.stringify({type: "auth", token: authToken}));
    } else { send.disabled = false; refreshFiles(); }
  } else if (m.type === "auth_ok") {
    send.disabled = false; status.textContent = "connected (authed)"; refreshFiles();
  } else if (m.type === "token") {
    if (!streamBubble) streamBubble = add("result", "");
    streamBubble.textContent += m.text;
    log.scrollTop = log.scrollHeight;
  } else if (m.type === "trace") {
    streamBubble = null;          // a trace line ends the current stream run
    add("trace", m.text);
  } else if (m.type === "workspace") {
    showWs(m.folders); refreshFiles();
  } else if (m.type === "result") {
    if (!streamBubble) add("result", m.result);  // non-streamed fallback
    streamBubble = null;
    busy = false; send.disabled = false; stop.disabled = true;
    status.textContent = "connected";
    addFileLinks(m.files);                        // files this run produced
    refreshFiles();                               // agent may have written files
  } else if (m.type === "error") {
    streamBubble = null;
    add("error", m.error);
    busy = false; send.disabled = false; stop.disabled = true;
  } else if (m.type === "hitl_confirm") {
    streamBubble = null;
    status.textContent = "awaiting your approval…";
    const ok = window.confirm(m.prompt || "Allow this high-risk tool call?");
    add(ok ? "trace" : "error", "[review] tool " + (ok ? "approved" : "denied"));
    ws.send(JSON.stringify({type: "hitl_response", id: m.id, result: ok}));
    status.textContent = "working… (Stop to interrupt)";
  } else if (m.type === "hitl_review") {
    streamBubble = null;
    status.textContent = "awaiting your review…";
    add("trace", "[review] " + (m.prompt || "Review this step"));
    if (m.content) add("result", m.content);
    let result;
    if (m.choices && m.choices.length) {          // ROUTE mode: pick a branch
      const opts = m.choices.map((c, i) => (i + 1) + ". " + c).join("\n");
      const ans = (window.prompt((m.prompt || "Choose the next step") +
        "\n\n" + opts + "\n\nEnter a number or name (default 1):", "1")
        || "").trim();
      let pick = m.choices[0];
      const n = parseInt(ans, 10);
      if (n >= 1 && n <= m.choices.length) pick = m.choices[n - 1];
      else if (m.choices.indexOf(ans) >= 0) pick = ans;
      result = {decision: pick, content: m.content || "", feedback: ""};
      add("trace", "[review] -> " + pick);
      ws.send(JSON.stringify({type: "hitl_response", id: m.id, result: result}));
      status.textContent = "working… (Stop to interrupt)";
      return;
    }
    const choice = (window.prompt((m.prompt || "Review this step") +
      "\n\nApprove this step? a = approve, e = edit, r = reject", "a")
      || "a").trim().toLowerCase();
    if (choice.startsWith("r")) {
      const fb = window.prompt("Rejection feedback (optional):", "") || "";
      result = {decision: "reject", content: m.content || "", feedback: fb};
      add("error", "[review] rejected");
    } else if (choice.startsWith("e")) {
      const edited = window.prompt("Edited content:", m.content || "");
      result = {decision: "edit",
                content: (edited === null ? (m.content || "") : edited),
                feedback: ""};
      add("trace", "[review] edited");
    } else {
      result = {decision: "approve", content: m.content || "", feedback: ""};
      add("trace", "[review] approved");
    }
    ws.send(JSON.stringify({type: "hitl_response", id: m.id, result: result}));
    status.textContent = "working… (Stop to interrupt)";
  }
};

function submit() {
  const task = input.value.trim();
  if (!task || busy || ws.readyState !== 1) return;
  const payload = {type: "task", task: task};
  if (pending.length) payload.images = pending;
  add("user", task + (pending.length ? "  [📎 " + pending.length +
                                        " image(s)]" : ""));
  ws.send(JSON.stringify(payload));
  pending = []; refreshAttachbar();
  input.value = ""; busy = true; send.disabled = true; stop.disabled = false;
  status.textContent = "working… (Stop to interrupt)";
}
send.onclick = submit;
stop.onclick = () => {
  if (!busy || ws.readyState !== 1) return;
  ws.send(JSON.stringify({type: "cancel"}));
  stop.disabled = true; status.textContent = "stopping…";
};
attach.onclick = () => fileInput.click();
fileInput.onchange = () => { addFiles(fileInput.files); fileInput.value = ""; };
["dragover", "drop"].forEach((ev) => document.addEventListener(ev, (e) => {
  if (!visionOn) return;
  e.preventDefault();
  if (ev === "drop" && e.dataTransfer) addFiles(e.dataTransfer.files);
}));
input.addEventListener("keydown", (e) => {
  if (e.key === "Enter" && (e.ctrlKey || e.metaKey)) submit();
});
</script>
</body></html>
"""

SERVER_CFG = core.CONFIG.get("server", {})
HOST = SERVER_CFG.get("host", "127.0.0.1")
PORT = int(SERVER_CFG.get("port", 8765))
TOKEN = SERVER_CFG.get("auth_token", "")
AUTO_ALLOW = bool(SERVER_CFG.get("auto_allow_tools", False))
# Extra Settings (opt-in; blank/0 = today's plain-ws / any-origin / unlimited):
TLS_CERT = SERVER_CFG.get("tls_cert", "")        # wss:// when both cert+key set
TLS_KEY = SERVER_CFG.get("tls_key", "")
ORIGINS = SERVER_CFG.get("allowed_origins") or None   # None = allow any Origin
MAX_CONNS = int(SERVER_CFG.get("max_connections", 0) or 0)   # 0 = unlimited

# One asyncio.Lock PER SESSION: a user's own turns serialize (no overlapping runs
# in one conversation), but different sessions run CONCURRENTLY. The generated
# runtime forks an isolated per-session state (core.run(session_id=…)), so there's
# no shared run state to protect globally. (The dict grows by one small lock per
# distinct session for the process lifetime — negligible.)
_SESSION_LOCKS: dict = {}
_CONNS = {"n": 0}           # live connection count (for MAX_CONNS)


def _session_lock(sid: str):
    lk = _SESSION_LOCKS.get(sid)
    if lk is None:
        lk = asyncio.Lock()
        _SESSION_LOCKS[sid] = lk
    return lk


def _msg(**fields) -> str:
    return json.dumps(fields, ensure_ascii=False)


# ── HITL bridge: prompt the browser and block the agent's worker thread ─────
# The agent runs on a background thread; when it hits a tool-confirm or review
# checkpoint we push a frame to the client and block that thread on an Event
# until the async handle() loop delivers the client's hitl_response (or a
# cancel/disconnect resolves it with a safe default).
_HITL_PENDING: dict = {}             # req_id -> {"event","result","default","owner"}
_HITL_BLOCK = threading.Lock()
_HITL_SEQ = {"n": 0}


def _next_hitl_id() -> int:
    with _HITL_BLOCK:
        _HITL_SEQ["n"] += 1
        return _HITL_SEQ["n"]


def _resolve_pending(owner=None) -> None:
    """Unblock worker threads waiting on a HITL answer, applying each request's
    safe default. `owner` (a session id) scopes it to ONE session's prompts — so a
    cancel / disconnect / run-end on one connection never force-resolves another
    concurrent session's live prompt. owner=None resolves all (process shutdown)."""
    with _HITL_BLOCK:
        ids = [i for i, s in _HITL_PENDING.items()
               if owner is None or s.get("owner") == owner]
        slots = [_HITL_PENDING.pop(i) for i in ids]
    for slot in slots:
        slot["result"] = slot["default"]
        slot["event"].set()


def _hitl_request(loop, queue, kind: str, payload: dict, default, owner=None):
    """(worker thread) send a HITL prompt to the browser, then block until the
    client answers — or a cancel/disconnect resolves it with `default`. `owner` is
    the session id, so only this session's answers / resolutions apply to it."""
    req_id = _next_hitl_id()
    slot = {"event": threading.Event(), "result": default, "default": default,
            "owner": owner}
    with _HITL_BLOCK:
        _HITL_PENDING[req_id] = slot
    loop.call_soon_threadsafe(queue.put_nowait, (kind, dict(payload, id=req_id)))
    slot["event"].wait()
    with _HITL_BLOCK:
        _HITL_PENDING.pop(req_id, None)
    return slot["result"]


async def _run_task(ws, task: str, images=None, session_id=None) -> None:
    loop = asyncio.get_running_loop()
    queue: asyncio.Queue = asyncio.Queue()

    def emit(text: str) -> None:
        loop.call_soon_threadsafe(queue.put_nowait, ("trace", text))

    def on_token(delta: str) -> None:
        loop.call_soon_threadsafe(queue.put_nowait, ("token", delta))

    # Per-CONNECTION HITL handlers, passed INTO core.run (which installs them on
    # this run's own state) — a global set_confirm_handler would race across
    # concurrent connections. When auto-allowing, approve without a round-trip.
    if AUTO_ALLOW:
        def _confirm(tool_name, args):
            return {"decision": "allow"}

        def _review(prompt, content, choices=None):
            # route mode: auto-pick the first branch; gate mode: auto-approve
            return {"decision": (choices[0] if choices else "approve"),
                    "content": content, "feedback": ""}
    else:
        def _confirm(tool_name, args):
            prompt = ("Allow high-risk tool '" + str(tool_name)
                      + "' with arguments:" + chr(10)
                      + json.dumps(args, ensure_ascii=False, indent=2))
            return bool(_hitl_request(
                loop, queue, "hitl_confirm", {"prompt": prompt}, default=False,
                owner=session_id))

        def _review(prompt, content, choices=None):
            # choices set => route mode: the browser shows a branch picker and
            # returns the chosen successor name in `decision`. Disconnect defaults
            # to the first branch (route) / reject (gate) so the run still finishes.
            _pay = {"prompt": prompt, "content": content or ""}
            if choices:
                _pay["choices"] = list(choices)
                _dflt = {"decision": choices[0], "content": content or "",
                         "feedback": "client disconnected"}
            else:
                _dflt = {"decision": "reject", "content": content or "",
                         "feedback": "client disconnected"}
            res = _hitl_request(loop, queue, "hitl_review", _pay,
                                default=_dflt, owner=session_id)
            return res if isinstance(res, dict) else {
                "decision": (choices[0] if choices else "approve"),
                "content": content or "", "feedback": ""}

    def work() -> None:
        try:
            # browser images arrive as base64 data URLs → neutral parts, passed
            # into run() so they land on THIS session's (possibly forked) state
            parts = []
            if images and hasattr(core, "decode_data_url"):
                for url in images:
                    try:
                        parts.append(core.decode_data_url(url))
                    except Exception:
                        pass
            before = _workspace_snapshot(session_id)
            result = core.run(task, emit=emit, on_token=on_token,
                              session_id=session_id, on_confirm=_confirm,
                              on_review=_review, image_parts=parts)
            produced = []
            for p, mt in _workspace_snapshot(session_id).items():
                if before.get(p) != mt:          # new or modified this run
                    try:
                        produced.append({"path": p, "name": os.path.basename(p),
                                         "size": os.path.getsize(p)})
                    except OSError:
                        pass
            loop.call_soon_threadsafe(queue.put_nowait, ("result", (result, produced)))
        except Exception as e:
            loop.call_soon_threadsafe(
                queue.put_nowait, ("error", f"{type(e).__name__}: {e}"))

    threading.Thread(target=work, daemon=True).start()
    while True:
        kind, payload = await queue.get()
        if kind == "token":
            await ws.send(_msg(type="token", text=payload))
        elif kind == "trace":
            await ws.send(_msg(type="trace", text=payload))
        elif kind in ("hitl_confirm", "hitl_review"):
            # forward the prompt; the worker thread is blocked awaiting the
            # client's hitl_response (handled live by handle()). Keep looping.
            await ws.send(_msg(type=kind, **payload))
        elif kind == "result":
            text, produced = payload
            await ws.send(_msg(type="result", result=text, files=produced))
            return
        elif kind == "error":
            await ws.send(_msg(type="error", error=payload))
            return


async def _run_with_lock(ws, task: str, images=None, session_id=None) -> None:
    async with _session_lock(session_id):      # serialize a session's OWN turns;
        try:                                    # different sessions run concurrently
            await _run_task(ws, task, images, session_id)
        except Exception:
            pass                               # e.g. the socket closed mid-stream
        finally:
            _resolve_pending(session_id)        # unblock only THIS session's prompt


async def handle(ws):
    if MAX_CONNS and _CONNS["n"] >= MAX_CONNS:
        await ws.send(_msg(type="error", error="server busy — too many connections"))
        await ws.close()
        return
    _CONNS["n"] += 1
    # Per-connection conversation id → each client gets its OWN history/memory
    # (no cross-talk between simultaneous browser tabs / gateway users). A client
    # may pin a stable id via the task frame's "session_id" (e.g. a gateway keying
    # by end-user) so a conversation survives reconnects; otherwise this ephemeral
    # per-connection id is used.
    conn_sid = "ws-" + os.urandom(8).hex()
    authed = not TOKEN
    _vision = bool(getattr(core, "entry_vision", lambda: False)())
    _ws = (core.get_workspace(session_id=conn_sid)
           if hasattr(core, "get_workspace") else [])
    run_task = None
    run_sid = conn_sid          # the session id of this connection's in-flight run
    try:
        await ws.send(_msg(type="hello", agent="ppbb",
                           auth_required=not authed, vision=_vision, workspace=_ws))
        async for raw in ws:
            try:
                msg = json.loads(raw)
            except json.JSONDecodeError:
                await ws.send(_msg(type="error", error="invalid JSON"))
                continue
            mtype = msg.get("type")
            if not authed:
                if mtype == "auth" and msg.get("token") == TOKEN:
                    authed = True
                    await ws.send(_msg(type="auth_ok"))
                else:
                    await ws.send(_msg(type="error", error="auth required"))
                    await ws.close()
                    return
                continue
            if mtype == "ping":
                await ws.send(_msg(type="pong"))
            elif mtype == "get_workspace":
                folders = (core.get_workspace(session_id=run_sid)
                           if hasattr(core, "get_workspace") else [])
                await ws.send(_msg(type="workspace", folders=folders))
            elif mtype == "set_workspace":     # set the folder agent files go to
                provided = [p for p in (msg.get("folders") or [])
                            if isinstance(p, str) and p.strip()]
                if hasattr(core, "set_workspace"):
                    core.set_workspace(provided, session_id=run_sid)   # per-session
                folders = (core.get_workspace(session_id=run_sid)
                           if hasattr(core, "get_workspace") else [])
                if provided and not folders:
                    await ws.send(_msg(type="trace",
                                       text="[workspace] path not found on the server: "
                                            + "; ".join(provided)))
                else:
                    await ws.send(_msg(type="trace", text="[workspace] "
                                       + ("set to " + "; ".join(folders) if folders else "cleared")))
                await ws.send(_msg(type="workspace", folders=folders))
            elif mtype == "hitl_response":     # answer to a confirm/review prompt
                slot = None
                with _HITL_BLOCK:
                    slot = _HITL_PENDING.get(msg.get("id"))
                # only answer prompts THIS connection owns — a connection must not
                # resolve another session's HITL slot (confused-deputy)
                if slot is not None and slot.get("owner") == run_sid:
                    slot["result"] = msg.get("result")
                    slot["event"].set()
            elif mtype == "cancel":            # Stop button in the web UI
                if hasattr(core, "request_cancel"):
                    core.request_cancel(session_id=run_sid)   # only THIS user's run
                    await ws.send(_msg(type="trace",
                                       text="[cancelling] stopping soon…"))
                _resolve_pending(run_sid)      # unblock THIS session's HITL prompt
            elif mtype == "task":
                # run in the background so this loop keeps reading (cancel/ping)
                if run_task and not run_task.done():
                    await ws.send(_msg(type="error",
                                       error="a run is already in progress"))
                    continue
                task = (msg.get("task") or "").strip()
                if not task:
                    await ws.send(_msg(type="error", error="empty task"))
                    continue
                images = msg.get("images") or []
                run_sid = (str(msg.get("session_id") or "").strip()) or conn_sid
                run_task = asyncio.create_task(
                    _run_with_lock(ws, task, images, run_sid))
            else:
                await ws.send(_msg(type="error", error=f"unknown type: {mtype}"))
    except websockets.exceptions.ConnectionClosed:
        pass                    # client vanished (tab closed / reset / proxy) — normal, not an error
    finally:
        _CONNS["n"] -= 1        # free the connection slot (MAX_CONNS)
        # stop any in-flight run if the client disconnects (only this session's)
        if (run_task and not run_task.done()
                and hasattr(core, "request_cancel")):
            core.request_cancel(session_id=run_sid)
        _resolve_pending(run_sid)   # unblock only THIS session's HITL waiter
        # drop this connection's per-session lock if idle, so a long-lived server
        # serving many short connections doesn't accumulate locks forever
        _lk = _SESSION_LOCKS.get(run_sid)
        if _lk is not None and not _lk.locked():
            _SESSION_LOCKS.pop(run_sid, None)


DOWNLOAD_MAX = 50 * 1024 * 1024     # cap a single web download at 50 MB


def _ws_realdirs(session_id=None) -> list:
    out = []
    for f in (core.get_workspace(session_id=session_id)
              if hasattr(core, "get_workspace") else []):
        try:
            out.append(os.path.realpath(f))
        except OSError:
            pass
    return out


def _safe_under_workspace(path: str):
    """realpath of `path` if it is a regular file inside a workspace folder,
    else None. realpath + commonpath blocks '..' traversal — only files under a
    configured workspace folder are ever served."""
    try:
        rp = os.path.realpath(path)
    except OSError:
        return None
    if not os.path.isfile(rp):
        return None
    for fr in _ws_realdirs():
        try:
            if os.path.commonpath([rp, fr]) == fr:
                return rp
        except ValueError:              # different drives (Windows)
            continue
    return None


def _list_workspace_files(limit: int = 500, session_id=None) -> list:
    items = []
    for fr in _ws_realdirs(session_id):
        for root, dirs, files in os.walk(fr):
            dirs[:] = [d for d in dirs if not d.startswith(".")]
            for name in sorted(files):
                if name.startswith("."):
                    continue
                full = os.path.join(root, name)
                try:
                    size = os.path.getsize(full)
                except OSError:
                    continue
                items.append({"path": full, "size": size,
                              "name": os.path.relpath(full, fr).replace(os.sep, "/")})
                if len(items) >= limit:
                    return items
    return items


def _workspace_snapshot(session_id=None) -> dict:
    """{abspath: mtime} of all workspace files — diffed before/after a run to
    surface the files that run produced."""
    snap = {}
    for it in _list_workspace_files(limit=10000, session_id=session_id):
        try:
            snap[it["path"]] = os.path.getmtime(it["path"])
        except OSError:
            pass
    return snap


def _authed_http(qs) -> bool:
    return (not TOKEN) or (qs.get("token", [""])[0] == TOKEN)


def process_request(connection, request):
    """Serve the chat web UI plus workspace file listing/downloads on plain HTTP
    GETs; let WebSocket upgrades continue to the handler."""
    if "Upgrade" in request.headers:
        return None
    parts = urlsplit(request.path)
    path, qs = parts.path, parse_qs(parts.query)
    if path in ("/", "/index.html"):
        response = connection.respond(http.HTTPStatus.OK, INDEX_HTML)
        try:
            del response.headers["Content-Type"]
        except KeyError:
            pass
        response.headers["Content-Type"] = "text/html; charset=utf-8"
        return response
    if path == "/files":
        if not _authed_http(qs):
            return connection.respond(http.HTTPStatus.UNAUTHORIZED, "auth required")
        body = json.dumps({"files": _list_workspace_files()}, ensure_ascii=False)
        resp = connection.respond(http.HTTPStatus.OK, body)
        try:
            del resp.headers["Content-Type"]
        except KeyError:
            pass
        resp.headers["Content-Type"] = "application/json; charset=utf-8"
        return resp
    if path == "/download":
        if not _authed_http(qs):
            return connection.respond(http.HTTPStatus.UNAUTHORIZED, "auth required")
        rp = _safe_under_workspace(unquote((qs.get("path") or [""])[0]))
        if not rp:
            return connection.respond(http.HTTPStatus.NOT_FOUND, "not in workspace")
        try:
            if os.path.getsize(rp) > DOWNLOAD_MAX:
                return connection.respond(http.HTTPStatus.FORBIDDEN,
                                          "file too large for web download")
            with open(rp, "rb") as fh:
                data = fh.read()
        except OSError:
            return connection.respond(http.HTTPStatus.NOT_FOUND, "not found")
        headers = Headers()
        headers["Content-Type"] = mimetypes.guess_type(rp)[0] or "application/octet-stream"
        headers["Content-Length"] = str(len(data))
        headers["Content-Disposition"] = (
            'attachment; filename="%s"' % os.path.basename(rp).replace('"', "_"))
        return Response(int(http.HTTPStatus.OK), "OK", headers, data)
    if path == "/zip":
        if not _authed_http(qs):
            return connection.respond(http.HTTPStatus.UNAUTHORIZED, "auth required")
        files = _list_workspace_files(limit=2000)
        if not files:
            return connection.respond(http.HTTPStatus.NOT_FOUND, "no files in workspace")
        if sum(f["size"] for f in files) > DOWNLOAD_MAX:
            return connection.respond(http.HTTPStatus.FORBIDDEN,
                                      "workspace too large to zip for web download")
        buf = io.BytesIO()
        seen = {}
        with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
            for f in files:
                rp = _safe_under_workspace(f["path"])
                if not rp:
                    continue
                arc = f["name"]
                if arc in seen:                 # de-collide names across folders
                    seen[arc] += 1
                    base, ext = os.path.splitext(arc)
                    arc = "%s_%d%s" % (base, seen[arc], ext)
                else:
                    seen[arc] = 0
                try:
                    z.write(rp, arc)
                except OSError:
                    pass
        data = buf.getvalue()
        headers = Headers()
        headers["Content-Type"] = "application/zip"
        headers["Content-Length"] = str(len(data))
        headers["Content-Disposition"] = 'attachment; filename="workspace.zip"'
        return Response(int(http.HTTPStatus.OK), "OK", headers, data)
    return connection.respond(http.HTTPStatus.NOT_FOUND, "not found")


async def main() -> None:
    # HITL is per-run now: each task passes its connection's confirm/review bridge
    # (or an auto-allow one) into core.run, so there's no global handler to install.
    _ssl = None
    if TLS_CERT and TLS_KEY:                     # wss:// (both required together)
        import ssl
        _ssl = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        _ssl.load_cert_chain(TLS_CERT, TLS_KEY)
    _scheme = "wss" if _ssl else "ws"
    _http = "https" if _ssl else "http"
    print(f"ppbb server on {_scheme}://{HOST}:{PORT}"
          + (" (auth token required)" if TOKEN else ""))
    print(f"Web UI: {_http}://{HOST}:{PORT}/")
    async with websockets.serve(handle, HOST, PORT,
                                process_request=process_request,
                                ssl=_ssl, origins=ORIGINS):
        await asyncio.Future()


if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        pass
